### ISSUE TITLE
Нет селекта с языками

### ISSUE THREAD

**Issue by failhell** [yiimaker/yii2-email-templates#2]
На форме добавления/редактирования шаблона, нет селекта для выбора языка. Мультиязычность есть, но пользоваться ей нельзя получается так)

**Comment by greeflas** [comment]
@failhell Исправлено в версии [1.1.1](https://github.com/yiimaker/yii2-email-templates/releases/tag/1.1.1). Спасибо!

**Comment by failhell** [comment]
Спасибо за быстрый фидбэк!

Отчасти работает, но появилось много нюансов:
1. Не видно какой же язык выбран. Например у меня меню из 8ми языков сразу трудно сообразить какой же выбран.
2. Было бы очень удобно видеть в общем списке шаблонов, отдельной колонкой, язык шаблона. Иначе ключ будет дублироваться и по нему не видно кто есть кто.
3. Если нажать редактировать шаблон затем сменить язык страница перезагружается и форма очищается (логично), но если вернуться на первоначальный язык, то форма все еще остается пустой и чтобы вернуть текст приходиться вернуться в общий список и опять искать тот шаблон и редактировать заново. Вроде бы мелочь но очень противная неудобность) Было бы гораздо удобнее чтоб страница не обновлялась. И гораздо удобнее переводить когда видишь текст. Обычный дропдавн или применить какой нибудь ништяк наподобие этого - http://www.yiiframework.com/extension/yii2-language-selector/
4. Тут же при редактировании шаблона. Как я понимаю связь в бд ключа шаблона и его переводов один ко многим. т.е. один ключ имеет несколько переводов. К тому же я видел метод который отдает шаблон по его ключу и языку. При этом, при смене языка (поля очистились), поле Хинт которое является обязательным и в тоже время disabled (и уже пустым) не дает сохранить форму без него. Таким образом создание нескольких переводов для одного ключа не является возможным в принципе (создание нового шаблона с таким же ключем но другим языком выбрасывает эксепшен, по поводу того, что такой ключ уже имеется).

Навскидку написал что сразу заметил. Пункты связаны друг с другом. Думаю если это пофиксить, то экстеншен будет в полне себе юзабелен!

Спасибо.

**Comment by greeflas** [comment]
@failhell спасибо за такой подробный фидбек! Возьму в работу в течении недели.

**Comment by greeflas** [comment]
@failhell 
1. В дропдауне с языками отображается выбранный язык.
2. Ключ в общем списке дублироватся не будет так как туда не выводятся все переводы. Только ключи, все переводы можно посмотреть в екшене view.
3. Создал шаблон на английском. Перешёл в редактирование и выбрал русский - страница перезагрузилась форма очистилась. Переключаюсь снова на английски  - исходные данные появились. Вроде бы всё работает, или я что-то не так понял?
4. Проблему с hint исправил, спасибо.

**Comment by failhell** [comment]
Обновил еще раз композер на всякий случай. Ничего не поменялось
1. не отображается выбранный язык весит всё время слово "Language". при смене меняется только ссылка &lang=ru.
2. Если так, то с этим согласен. Думал что в таблице задумывалось выводить все шаблоны с фильтрами и сортировками.
3. Странно если так. потому что у меня не подтягиваются данные, как и не подтягивается изначально заданный язык в селектор при первом переходе в редактирование.
4. Отлично.

**Comment by greeflas** [comment]
@failhell возможно у вас стоит старая версия, пропишите в `composer.json` -  `"yiimaker/yii2-email-templates": "dev-master"` и выполните команду `composer update yiimaker/yii2-email-templates`.

**Comment by failhell** [comment]
обновился.

**Comment by failhell** [comment]
Illegal string offset 'label'
in ...../vendor/yiimaker/yii2-email-templates/src/widgets/views/languages.php

**Comment by failhell** [comment]
мне ide пишет что у контекста нет currentLanguage вообще

**Comment by greeflas** [comment]
@failhell кажется вы неправильно настроили language provider. IDE не может знать что находится в контексте, это нормально что нет подсветки.

**Comment by failhell** [comment]
Конфиг взял из доки. 
`'email-templates' => [
            'class' => \ymaker\email\templates\Module::class,
            'languageProvider' => [
                'class' => \yii2deman\tools\i18n\ConfigLanguageProvider::class,
                'languages' => [
                    [
                        'locale' => 'en',
                        'label' => 'English',
                    ],
                    [
                        'locale' => 'ru',
                        'label' => 'Russian',
                    ],
                ],
                'defaultLanguage' => [
                    'locale' => 'en',
                    'label' => 'English',
                ],
            ],
        ],`

**Comment by greeflas** [comment]
@failhell хм, странно. Изменил немного логику, попробуйте обновиться.

**Comment by failhell** [comment]
ошибка ушла, только теперь какой-то баг получился с полем сабджект.
прямо под инпутом выводится текст (еще раз содержимое инпута) и скобки квадратные
`[] test`

**Comment by greeflas** [comment]
@failhell это вывод текста первого шаблона в качестве подсказки. В скобках должен выводится язык этого шаблона. Попробуйте создать новый шаблон.

**Comment by failhell** [comment]
создал новый и нажал редактировать.
получилось такое: http://joxi.ru/KAgGL9QU4GQ0eA

если в селекте выбрать англ в ручную то поля подтянутся

**Comment by greeflas** [comment]
@failhell значит у вас не настроена опция `language` в настройках приложения.
Эта опция и значение locale в настройках  стандартного языка в настройках language provider должны быть одинаковыми.

Вот пример:
```php
// common/config/main.php
return [
    'language' => 'en', // default language locale

    'modules' => [
        'email-templates' => [
            'class' => \ymaker\email\templates\Module::class,
            'languageProvider' => [
                'class' => \yii2deman\tools\i18n\ConfigLanguageProvider::class,
                'languages' => [
                    [
                        'locale' => 'en',
                        'label' => 'English',
                    ],
                    // ...
                ],
                'defaultLanguage' => [
                    'locale' => 'en', // value should be the same as in language property in app config
                    'label' => 'English',
                ],
            ],
        ],
    ],
];
```

Issue #3

**Comment by failhell** [comment]
да. работает)
Спасибо
эти подсказки вы уберете?

**Comment by greeflas** [comment]
@failhell пока не планирую, думаю добавлю возможность отключать эти подсказки в конфигурации модуля.

**Comment by failhell** [comment]
ok. Думаю что здесь пока все. Спасибо!
Пойду пробовать с большим количеством языков.

**Comment by greeflas** [comment]
@failhell вам спасибо за фидбек! Удачи :)
