### ISSUE TITLE
Responsiveness index

### ISSUE THREAD

**Issue by Geoffry304** [yiimaker/yii2-email-templates#23]
Hello 

The index page is not responsive, you should remove the container class and the problem will be solved

With container
![image](https://user-images.githubusercontent.com/3656871/40475302-8a34ada4-5f41-11e8-91c3-56b48b1a49b4.png)

Without container
![image](https://user-images.githubusercontent.com/3656871/40475323-99effba4-5f41-11e8-8b9e-748618c784ba.png)

**Comment by Geoffry304** [comment]
it is the same for every view

**Comment by greeflas** [comment]
@Geoffry304 It works well with default Bootstrap. You can always override extension view files using Yii themes.

**Comment by greeflas** [comment]
@Geoffry304 But you can create pull request with these changes. It's not critical for extension work so I can merge your request.

**Comment by Geoffry304** [comment]
well for me it is the default bootstrap together with admin lte. I will check to override the view files thanks

**Comment by greeflas** [comment]
@Geoffry304 Yes, I mean bootstrap without any themes like Admin LTE.
