### ISSUE TITLE
Not instantiable error using TemplateManager component

### ISSUE THREAD

**Issue by cccaballero** [yiimaker/yii2-email-templates#32]
I am getting a "Not instantiable" error when using the TemplateManager component, I have declared it in the config like:

    //...
    'components' => [
        //...
        'TemplateManager' => [
            'class' => \ymaker\email\templates\components\TemplateManager::class,
        ],
        //...
    ],

and the error is triggered when I call:

    \Yii::$app->get('templateManager');

Other features like the GII generator and the backend module seems to be working ok.

I am using Yii 2.0.14.2 and PHP 7.2.3

**Comment by greeflas** [comment]
@cccaballero Hi! I think you might have missed configuration for repository. Please check docs
https://github.com/yiimaker/yii2-email-templates/blob/master/docs/guide/template-manager.md#configuration

**Comment by cccaballero** [comment]
Damn!! That's a RTFM question... Everything is fine now, thanks. Great extension by the way!!.

**Comment by greeflas** [comment]
@cccaballero Good. Thank you :)
