### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by easydowork** [yiimaker/yii2-email-templates#34]
I want to configure the system to send an error message. But the view is not friendly when looking at the phone. Can you write a beautiful view ? thinks

**Comment by greeflas** [comment]
@crazePhper Hi! Do you mean [bootstrap views](https://github.com/yiimaker/yii2-email-templates/tree/master/src/views/default) in the backend module?

**Comment by easydowork** [comment]
yes, the class yii\log\EmailTarget ,I config it to send error message,it's not  friendly

**Comment by greeflas** [comment]
@crazePhper sorry, I don't get how you are using this extension with `yii\log\EmailTarget`. Can you add some code example?

**Comment by easydowork** [comment]
in the file main.php,config the components->mailer like this:
```
'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.qq.com',
                'port' => 465,
                'encryption' => 'ssl',
                'username' => '*****',
                'password' => '*****',
            ],
            'messageConfig' => [
                'charset' => 'utf-8',
                'from' => ['*****@mail.com' => '***']
            ],
        ],
```
then config components->log->targets like this:
```
'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\EmailTarget',
                    'levels' => ['error'],
                    'categories' => ['yii\db\*'],
                    'message' => [
                        'from' => ['***@mail.com'],
                        'to' => ['***@mail.com'],
                        'subject' => 'email title',
                    ],
                ],
            ],
        ],
```
when the yii2 has db error,it will send message to my mail box ,but the defaule view not friendly  you can    try config it ,and it will tell you

**Comment by greeflas** [comment]
@crazePhper okay, but this functionality is not related to this module. `yii\swiftmailer\Mailer`, `yii\log\EmailTarget` it's core Yii framework components.

This extension doesn't provide beautiful views but possibility to use kind of variables in your email letters.

**Comment by easydowork** [comment]
thinks for your answer,I will overwrith EmailTarget
