### ISSUE TITLE
Redactor not working anymore?

### ISSUE THREAD

**Issue by Geoffry304** [yiimaker/yii2-email-templates#35]
![image](https://user-images.githubusercontent.com/3656871/48772307-5181b400-ecc4-11e8-9496-39a344299bad.png)

I have no wysiwyg editor anymore?

**Comment by greeflas** [comment]
Hi @Geoffry304 ! Sience 4.x version, `vova07/yii2-imperavi-widget` moved from requirements. You can use  your redactor or install `vova07/yii2-imperavi-widget`. If you'll install `vova07/yii2-imperavi-widget` you'll see WYSIWYG editor in your admin panel.

All these changes described in the [UPGRADE.md](https://github.com/yiimaker/yii2-email-templates/blob/master/UPGRADE.md#upgrade-from-3x-to-4x) document.
