### ISSUE TITLE
Not able to reach the generator

### ISSUE THREAD

**Issue by camillo18tre** [yiimaker/yii2-email-templates#37]
Hi!
I configured the extension and generated the tables trough migrate. 
How can I reach the generator in my browser?

Thank you.

C.

**Comment by greeflas** [comment]
Hi @camillo18tre ! You just need to add email template generator to your Gii configuration like in [this example](https://github.com/yiimaker/yii2-email-templates/blob/master/docs/guide/gii-generator.md).

**Comment by camillo18tre** [comment]
Thank you for your quick answer. I meant like the action that I found in your code like: 
"http://mybasicurl/email-templates/default/create"

**Comment by greeflas** [comment]
@camillo18tre you need to add module to your application config. Check [Backend module](https://github.com/yiimaker/yii2-email-templates/blob/master/docs/guide/installation.md#backend-module) section of installation instruction.

**Comment by camillo18tre** [comment]
Thank you!
