### ISSUE TITLE
unique validation not working

### ISSUE THREAD

**Issue by AjithLalps** [yiimaker/yii2-email-templates#4]
unique validation added for filed **key** is not working and getting error while creating an email template with same key as the previous one.
![email-template](https://user-images.githubusercontent.com/18158025/30374873-13764a4c-98a4-11e7-9658-7810d368a49c.png)

**Comment by greeflas** [comment]
@AjithLalps what version are you using?

**Comment by AjithLalps** [comment]
version 2.0.0

**Comment by greeflas** [comment]
@AjithLalps try update your version to [2.1.0](https://github.com/yiimaker/yii2-email-templates/releases/tag/2.1.0)

**Comment by AjithLalps** [comment]
@greeflas this issue has been fixed in version 2.1.0
