### ISSUE TITLE
showing only one validation error message when submitting blank form

### ISSUE THREAD

**Issue by AjithLalps** [yiimaker/yii2-email-templates#5]
**issue**
when submitting a blank form only field key required validation message is showing instead of all field validations.

**extension version**
version 2.1.0

**steps to regenerate**
step 1: click on create button from index page.
step 2: submit the form without filling the fields.

**additional info**

![screenshot-admin etransglobal yii-2017-09-14-14-42-47](https://user-images.githubusercontent.com/18158025/30421779-7b39833a-995b-11e7-8075-2a0b0295bbc4.png)

**Comment by greeflas** [comment]
@AjithLalps was fixed in 20ac821 commit. Thank you!
