### ISSUE TITLE
А где message source?

### ISSUE THREAD

**Issue by maxodrom** [yiimaker/yii2-email-templates#50]
```php
Invalid Configuration – yii\base\InvalidConfigException
Unable to locate message source for category 'back/email-templates'.
```

**Comment by greeflas** [comment]
@maxodrom К сожалению данный пакет не предоставляет файлов с переводами. Переводы уходят на сторону разработчика приложения.

Вы можете создать pull request добавив файлы с переводами.

**Comment by maxodrom** [comment]
@greeflas https://github.com/yiimaker/yii2-email-templates/pull/51
