### ISSUE TITLE
More complex widgets within template

### ISSUE THREAD

**Issue by philippfrenzel** [yiimaker/yii2-email-templates#8]
Hi,

I would like to not only put text placeholder within the template - I would need placeholders for widgets which can although accept parameters - is this working already? How much code change would it need to make it possible?

Thanks Philipp

**Comment by greeflas** [comment]
@philippfrenzel Do you can give an example in code? How it must work?

**Comment by philippfrenzel** [comment]
Hi, should work like:
```php
$template->parseBody([
   'username' => Yii::$app->getIdentity()->username,
   'site-name' => Yii::$app->name,
   'html-report-widget' => \app\modules\reports\widgets\report\MyFancyHtmlWidget(['param1' => 1,'param2' => Yii::$app->user->id])
]);
```
Hope this makes it clear?

**Comment by philippfrenzel** [comment]
Btw - nothing "must" would be nice if it could ;)

**Comment by greeflas** [comment]
@philippfrenzel You already can use code from your example :)

**Comment by philippfrenzel** [comment]
Great - thanks so maybe update your docs ;)

**Comment by greeflas** [comment]
Of course #9
