### ISSUE TITLE
Call to undefined method ymaker\email\templates\models\EmailTemplate::find()

### ISSUE THREAD

**Issue by fiSCIENCES** [yiimaker/yii2-email-templates#86]
Hi,

I try to make et getter in EmailTemplateTranslation for the relation to EmailTemplate like this:
`    public function getTemplate(): ActiveQuery|EmailTemplateQuery
    {
        return $this->hasOne(EmailTemplate::class, ['id' => 'templateId']);
    }
`
and then access it like this:
`$model->template->key` or `'value' => 'template.key'`in a GridView

but I get this error:
`Call to undefined method ymaker\email\templates\models\EmailTemplate::find()`

Did I configure something wrong or is it really missing the find().
Because everything works great except this.

Thank you

**Comment by greeflas** [comment]
Hi @fiSCIENCES,

try to use [ymaker\email\templates\entities\EmailTemplate](https://github.com/yiimaker/yii2-email-templates/blob/master/src/entities/EmailTemplate.php) entity instead of model class.

**Comment by fiSCIENCES** [comment]
Hi @greeflas,

Thank you for your answer. I'm relatively new to Yii2, could you explain a little more.

Thank you again.

**Comment by fiSCIENCES** [comment]
Hi,

Find out this:
        return $this->hasOne('ymaker\email\templates\entities\EmailTemplate', ['id' => 'templateId']);
does the job.

Thank you!
