### ISSUE TITLE
Migration wrong in safeDown()

### ISSUE THREAD

**Issue by fiSCIENCES** [yiimaker/yii2-email-templates#87]
*** reverting ymaker\email\templates\migrations\m171119_140800_create_email_template_entities
    > drop foreign key fk-email_template_translation-email_template from table {{%email_template}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'fk-email_template_translation-email_template'; check that column/key exists

Wrong table selected in the safeDown(), should be "translationTableName".

**Comment by greeflas** [comment]
Fix in PR #85

**Comment by greeflas** [comment]
Fixed in [v4.1.2](https://github.com/yiimaker/yii2-email-templates/releases/tag/v4.1.2).
